// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"fmt"

	"go.opentelemetry.io/collector/confmap"
)

// PprofBlockContentionsMetricConfig provides config for the pprof.block.contentions metric.
type PprofBlockContentionsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *PprofBlockContentionsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// PprofBlockDelayMetricConfig provides config for the pprof.block.delay metric.
type PprofBlockDelayMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *PprofBlockDelayMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// PprofCPUUtilizationMetricConfig provides config for the pprof.cpu.utilization metric.
type PprofCPUUtilizationMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *PprofCPUUtilizationMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// PprofMemoryAllocatedBytesMetricConfig provides config for the pprof.memory.allocated.bytes metric.
type PprofMemoryAllocatedBytesMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *PprofMemoryAllocatedBytesMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// PprofMemoryAllocatedObjectsMetricConfig provides config for the pprof.memory.allocated.objects metric.
type PprofMemoryAllocatedObjectsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *PprofMemoryAllocatedObjectsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// PprofMemoryHeapFragmentationMetricConfig provides config for the pprof.memory.heap.fragmentation metric.
type PprofMemoryHeapFragmentationMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *PprofMemoryHeapFragmentationMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// PprofMemoryInuseBytesMetricConfig provides config for the pprof.memory.inuse.bytes metric.
type PprofMemoryInuseBytesMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *PprofMemoryInuseBytesMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// PprofMemoryInuseObjectsMetricConfig provides config for the pprof.memory.inuse.objects metric.
type PprofMemoryInuseObjectsMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *PprofMemoryInuseObjectsMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// PprofMemoryObjectAvgSizeMetricConfig provides config for the pprof.memory.object.avg_size metric.
type PprofMemoryObjectAvgSizeMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *PprofMemoryObjectAvgSizeMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SamplesBeamCountMetricConfig provides config for the samples.beam.count metric.
type SamplesBeamCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SamplesBeamCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SamplesClassificationMetricAttributeKey specifies the key of an attribute for the samples.classification metric.
type SamplesClassificationMetricAttributeKey string

const (
	SamplesClassificationMetricAttributeKeyClassification  SamplesClassificationMetricAttributeKey = "classification"
	SamplesClassificationMetricAttributeKeyFrameType       SamplesClassificationMetricAttributeKey = "frame_type"
	SamplesClassificationMetricAttributeKeyProfileTypeUnit SamplesClassificationMetricAttributeKey = "profile.type_unit"
)

// SamplesClassificationMetricConfig provides config for the samples.classification metric.
type SamplesClassificationMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                    `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SamplesClassificationMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *SamplesClassificationMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SamplesClassificationMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SamplesClassificationMetricAttributeKeyClassification, SamplesClassificationMetricAttributeKeyFrameType, SamplesClassificationMetricAttributeKeyProfileTypeUnit:
		default:
			return fmt.Errorf("metric samples.classification doesn't have an attribute %v, valid attributes: [classification, frame_type, profile.type_unit]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SamplesCpythonCountMetricConfig provides config for the samples.cpython.count metric.
type SamplesCpythonCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SamplesCpythonCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SamplesCustomAggregationMetricAttributeKey specifies the key of an attribute for the samples.custom_aggregation metric.
type SamplesCustomAggregationMetricAttributeKey string

const (
	SamplesCustomAggregationMetricAttributeKeyFrameType       SamplesCustomAggregationMetricAttributeKey = "frame_type"
	SamplesCustomAggregationMetricAttributeKeyProfileTypeUnit SamplesCustomAggregationMetricAttributeKey = "profile.type_unit"
)

// SamplesCustomAggregationMetricConfig provides config for the samples.custom_aggregation metric.
type SamplesCustomAggregationMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                                       `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SamplesCustomAggregationMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *SamplesCustomAggregationMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SamplesCustomAggregationMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SamplesCustomAggregationMetricAttributeKeyFrameType, SamplesCustomAggregationMetricAttributeKeyProfileTypeUnit:
		default:
			return fmt.Errorf("metric samples.custom_aggregation doesn't have an attribute %v, valid attributes: [frame_type, profile.type_unit]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SamplesDotnetCountMetricConfig provides config for the samples.dotnet.count metric.
type SamplesDotnetCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SamplesDotnetCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SamplesFrameTypeMetricAttributeKey specifies the key of an attribute for the samples.frame_type metric.
type SamplesFrameTypeMetricAttributeKey string

const (
	SamplesFrameTypeMetricAttributeKeyFrameType       SamplesFrameTypeMetricAttributeKey = "frame_type"
	SamplesFrameTypeMetricAttributeKeyProfileTypeUnit SamplesFrameTypeMetricAttributeKey = "profile.type_unit"
)

// SamplesFrameTypeMetricConfig provides config for the samples.frame_type metric.
type SamplesFrameTypeMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool

	AggregationStrategy string                               `mapstructure:"aggregation_strategy"`
	EnabledAttributes   []SamplesFrameTypeMetricAttributeKey `mapstructure:"attributes"`
}

func (ms *SamplesFrameTypeMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

func (ms *SamplesFrameTypeMetricConfig) Validate() error {
	for _, val := range ms.EnabledAttributes {
		switch val {
		case SamplesFrameTypeMetricAttributeKeyFrameType, SamplesFrameTypeMetricAttributeKeyProfileTypeUnit:
		default:
			return fmt.Errorf("metric samples.frame_type doesn't have an attribute %v, valid attributes: [frame_type, profile.type_unit]", val)
		}
	}

	switch ms.AggregationStrategy {
	case AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax:
	default:
		return fmt.Errorf("invalid aggregation strategy %q, valid strategies: [%s, %s, %s, %s]", ms.AggregationStrategy, AggregationStrategySum, AggregationStrategyAvg, AggregationStrategyMin, AggregationStrategyMax)
	}

	return nil
}

// SamplesGoCountMetricConfig provides config for the samples.go.count metric.
type SamplesGoCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SamplesGoCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SamplesJvmCountMetricConfig provides config for the samples.jvm.count metric.
type SamplesJvmCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SamplesJvmCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SamplesKernelCountMetricConfig provides config for the samples.kernel.count metric.
type SamplesKernelCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SamplesKernelCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SamplesNativeCountMetricConfig provides config for the samples.native.count metric.
type SamplesNativeCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SamplesNativeCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SamplesPerlCountMetricConfig provides config for the samples.perl.count metric.
type SamplesPerlCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SamplesPerlCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SamplesPhpCountMetricConfig provides config for the samples.php.count metric.
type SamplesPhpCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SamplesPhpCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SamplesRubyCountMetricConfig provides config for the samples.ruby.count metric.
type SamplesRubyCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SamplesRubyCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SamplesRustCountMetricConfig provides config for the samples.rust.count metric.
type SamplesRustCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SamplesRustCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SamplesUserCountMetricConfig provides config for the samples.user.count metric.
type SamplesUserCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SamplesUserCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// SamplesV8jsCountMetricConfig provides config for the samples.v8js.count metric.
type SamplesV8jsCountMetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *SamplesV8jsCountMetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for profilingmetrics metrics.
type MetricsConfig struct {
	PprofBlockContentions        PprofBlockContentionsMetricConfig        `mapstructure:"pprof.block.contentions"`
	PprofBlockDelay              PprofBlockDelayMetricConfig              `mapstructure:"pprof.block.delay"`
	PprofCPUUtilization          PprofCPUUtilizationMetricConfig          `mapstructure:"pprof.cpu.utilization"`
	PprofMemoryAllocatedBytes    PprofMemoryAllocatedBytesMetricConfig    `mapstructure:"pprof.memory.allocated.bytes"`
	PprofMemoryAllocatedObjects  PprofMemoryAllocatedObjectsMetricConfig  `mapstructure:"pprof.memory.allocated.objects"`
	PprofMemoryHeapFragmentation PprofMemoryHeapFragmentationMetricConfig `mapstructure:"pprof.memory.heap.fragmentation"`
	PprofMemoryInuseBytes        PprofMemoryInuseBytesMetricConfig        `mapstructure:"pprof.memory.inuse.bytes"`
	PprofMemoryInuseObjects      PprofMemoryInuseObjectsMetricConfig      `mapstructure:"pprof.memory.inuse.objects"`
	PprofMemoryObjectAvgSize     PprofMemoryObjectAvgSizeMetricConfig     `mapstructure:"pprof.memory.object.avg_size"`
	SamplesBeamCount             SamplesBeamCountMetricConfig             `mapstructure:"samples.beam.count"`
	SamplesClassification        SamplesClassificationMetricConfig        `mapstructure:"samples.classification"`
	SamplesCpythonCount          SamplesCpythonCountMetricConfig          `mapstructure:"samples.cpython.count"`
	SamplesCustomAggregation     SamplesCustomAggregationMetricConfig     `mapstructure:"samples.custom_aggregation"`
	SamplesDotnetCount           SamplesDotnetCountMetricConfig           `mapstructure:"samples.dotnet.count"`
	SamplesFrameType             SamplesFrameTypeMetricConfig             `mapstructure:"samples.frame_type"`
	SamplesGoCount               SamplesGoCountMetricConfig               `mapstructure:"samples.go.count"`
	SamplesJvmCount              SamplesJvmCountMetricConfig              `mapstructure:"samples.jvm.count"`
	SamplesKernelCount           SamplesKernelCountMetricConfig           `mapstructure:"samples.kernel.count"`
	SamplesNativeCount           SamplesNativeCountMetricConfig           `mapstructure:"samples.native.count"`
	SamplesPerlCount             SamplesPerlCountMetricConfig             `mapstructure:"samples.perl.count"`
	SamplesPhpCount              SamplesPhpCountMetricConfig              `mapstructure:"samples.php.count"`
	SamplesRubyCount             SamplesRubyCountMetricConfig             `mapstructure:"samples.ruby.count"`
	SamplesRustCount             SamplesRustCountMetricConfig             `mapstructure:"samples.rust.count"`
	SamplesUserCount             SamplesUserCountMetricConfig             `mapstructure:"samples.user.count"`
	SamplesV8jsCount             SamplesV8jsCountMetricConfig             `mapstructure:"samples.v8js.count"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		PprofBlockContentions: PprofBlockContentionsMetricConfig{
			Enabled: false,
		},
		PprofBlockDelay: PprofBlockDelayMetricConfig{
			Enabled: false,
		},
		PprofCPUUtilization: PprofCPUUtilizationMetricConfig{
			Enabled: true,
		},
		PprofMemoryAllocatedBytes: PprofMemoryAllocatedBytesMetricConfig{
			Enabled: true,
		},
		PprofMemoryAllocatedObjects: PprofMemoryAllocatedObjectsMetricConfig{
			Enabled: true,
		},
		PprofMemoryHeapFragmentation: PprofMemoryHeapFragmentationMetricConfig{
			Enabled: false,
		},
		PprofMemoryInuseBytes: PprofMemoryInuseBytesMetricConfig{
			Enabled: true,
		},
		PprofMemoryInuseObjects: PprofMemoryInuseObjectsMetricConfig{
			Enabled: true,
		},
		PprofMemoryObjectAvgSize: PprofMemoryObjectAvgSizeMetricConfig{
			Enabled: false,
		},
		SamplesBeamCount: SamplesBeamCountMetricConfig{
			Enabled: true,
		},
		SamplesClassification: SamplesClassificationMetricConfig{
			Enabled:             false,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []SamplesClassificationMetricAttributeKey{SamplesClassificationMetricAttributeKeyClassification, SamplesClassificationMetricAttributeKeyFrameType, SamplesClassificationMetricAttributeKeyProfileTypeUnit},
		},
		SamplesCpythonCount: SamplesCpythonCountMetricConfig{
			Enabled: true,
		},
		SamplesCustomAggregation: SamplesCustomAggregationMetricConfig{
			Enabled:             true,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []SamplesCustomAggregationMetricAttributeKey{SamplesCustomAggregationMetricAttributeKeyFrameType, SamplesCustomAggregationMetricAttributeKeyProfileTypeUnit},
		},
		SamplesDotnetCount: SamplesDotnetCountMetricConfig{
			Enabled: true,
		},
		SamplesFrameType: SamplesFrameTypeMetricConfig{
			Enabled:             false,
			AggregationStrategy: AggregationStrategyAvg,
			EnabledAttributes:   []SamplesFrameTypeMetricAttributeKey{SamplesFrameTypeMetricAttributeKeyFrameType, SamplesFrameTypeMetricAttributeKeyProfileTypeUnit},
		},
		SamplesGoCount: SamplesGoCountMetricConfig{
			Enabled: true,
		},
		SamplesJvmCount: SamplesJvmCountMetricConfig{
			Enabled: true,
		},
		SamplesKernelCount: SamplesKernelCountMetricConfig{
			Enabled: true,
		},
		SamplesNativeCount: SamplesNativeCountMetricConfig{
			Enabled: true,
		},
		SamplesPerlCount: SamplesPerlCountMetricConfig{
			Enabled: true,
		},
		SamplesPhpCount: SamplesPhpCountMetricConfig{
			Enabled: true,
		},
		SamplesRubyCount: SamplesRubyCountMetricConfig{
			Enabled: true,
		},
		SamplesRustCount: SamplesRustCountMetricConfig{
			Enabled: true,
		},
		SamplesUserCount: SamplesUserCountMetricConfig{
			Enabled: true,
		},
		SamplesV8jsCount: SamplesV8jsCountMetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for profilingmetrics metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func NewDefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}

// Deprecated: Use NewDefaultMetricsBuilderConfig.
func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return NewDefaultMetricsBuilderConfig()
}
